### ISSUE TITLE
Add steps to create multi-node local test network

### ISSUE THREAD

**Issue by han-so1omon** [icon-project/devportal#58]
### What needs to be done

Need to add steps to create local multi-node test network

### Why it needs to be done

This is important for project debugging

### Tests

Link associated tests here

### Stories

As a developer, I should be able to create a local, multi-node test network

### Acceptance Criteria

- [ ] Proof of test run from start to finish. Include photos from start to finish

### Additional Information

See info from Discord users 'espanicon' and 'Aj| ICONosphere'

https://discord.com/channels/880651922682560582/888476176237080687/1072755735332663296

```
#Aj| ICONosphere
You would need to activate IISS features. There were 3 criteria for that. Let me try to find it.
```

```
#espanicon
after getting the local chain up and running is necessary to do these steps:


* send icx from God wallet to the 4 node wallets 
* run the 'registerPrep' command to make those wallets validators
* self stake and self bond on each wallet so that they can start producing blocks
```

```
#Aj| ICONosphere
To decentralize your network, the following conditions are required:
1. # of registered preps >= main prep count
2. The last main prep's power should be more than totalSupply * 0.2% in power descending order.
3. revision >= 6
```

**Comment by FidelVe** [comment]
self assigning this task to create a tutorial that will describe how to create a local multi-node network and then decentralizing the network by registering preps, staking, voting and setting up bond.

**Comment by FidelVe** [comment]
added draft to gitbook
https://app.gitbook.com/o/-McMmnDTovEDTOOjq4sG/s/-McMmuxKCCgDfbGouV8t-887967055/~/changes/206/getting-started/how-to-run-a-local-network/decentralizing-a-local-network/~/comments/bGXPfBkOO3O2zVcNl4aV

**Comment by FidelVe** [comment]
Done
https://github.com/icon-project/devportal/commit/47ee985a8ece8e38270f6c5bf6cb5ff692f36c53
